WIDTH = 800
HEIGHT = 800
SCOREBOARD_WIDTH = 300
SCREEN_SIZE = (WIDTH, HEIGHT)
WINDOW_SIZE = (WIDTH + SCOREBOARD_WIDTH, HEIGHT)

BACKGROUND_COLOUR = (230, 230, 255)
FPS = 60

LIFE_INIT = 2

TIME_SCORE = 1
HIT_SCORE = 5
