WIDTH = 768
HEIGHT = 896
SCOREBOARD_WIDTH = 300

MARGIN_LEFT = 64
MARGIN_TOP = 32
MARGIN_BOTTOM = 32
MARGIN_BOTTOM_TOP = MARGIN_TOP + HEIGHT

SCOREBOARD_LEFT = MARGIN_LEFT + WIDTH
SCOREBOARD_WIDTH = 448

WINDOW_WIDTH = SCOREBOARD_LEFT + SCOREBOARD_WIDTH
WINDOW_HEIGHT = MARGIN_BOTTOM_TOP + MARGIN_BOTTOM

GAME_RECT = (MARGIN_LEFT, MARGIN_TOP, WIDTH, HEIGHT)

FPS = 60

LIFE_INIT = 2

TIME_SCORE = 1
HIT_SCORE = 5
